# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
