# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={},
        ),
    ]
